//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace QLEX {

public class EnergyVanillaSwapExt : EnergySwapExt {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal EnergyVanillaSwapExt(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.EnergyVanillaSwapExt_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EnergyVanillaSwapExt obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EnergyVanillaSwapExt() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NQuantLibcPINVOKE.delete_EnergyVanillaSwapExt(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public EnergyVanillaSwapExt(bool payer, double fixedPrice, CommodityIndexExt index, PricingPeriodExts PricingPeriodExts, string commodityName, YieldTermStructureHandle payLegTermStructure, YieldTermStructureHandle receiveLegTermStructure, Frequency deliverySchedule, Calendar calendar) : this(NQuantLibcPINVOKE.new_EnergyVanillaSwapExt__SWIG_0(payer, fixedPrice, CommodityIndexExt.getCPtr(index), PricingPeriodExts.getCPtr(PricingPeriodExts), commodityName, YieldTermStructureHandle.getCPtr(payLegTermStructure), YieldTermStructureHandle.getCPtr(receiveLegTermStructure), (int)deliverySchedule, Calendar.getCPtr(calendar)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public EnergyVanillaSwapExt(bool payer, double fixedPrice, CommodityIndexExt index, PricingPeriodExts PricingPeriodExts, string commodityName, YieldTermStructureHandle payLegTermStructure, YieldTermStructureHandle receiveLegTermStructure, Frequency deliverySchedule) : this(NQuantLibcPINVOKE.new_EnergyVanillaSwapExt__SWIG_1(payer, fixedPrice, CommodityIndexExt.getCPtr(index), PricingPeriodExts.getCPtr(PricingPeriodExts), commodityName, YieldTermStructureHandle.getCPtr(payLegTermStructure), YieldTermStructureHandle.getCPtr(receiveLegTermStructure), (int)deliverySchedule), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public EnergyVanillaSwapExt(bool payer, double fixedPrice, CommodityIndexExt index, PricingPeriodExts PricingPeriodExts, string commodityName, YieldTermStructureHandle payLegTermStructure, YieldTermStructureHandle receiveLegTermStructure) : this(NQuantLibcPINVOKE.new_EnergyVanillaSwapExt__SWIG_2(payer, fixedPrice, CommodityIndexExt.getCPtr(index), PricingPeriodExts.getCPtr(PricingPeriodExts), commodityName, YieldTermStructureHandle.getCPtr(payLegTermStructure), YieldTermStructureHandle.getCPtr(receiveLegTermStructure)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public CommodityIndexExt index() {
    CommodityIndexExt ret = new CommodityIndexExt(NQuantLibcPINVOKE.EnergyVanillaSwapExt_index(swigCPtr), true);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int payReceive() {
    int ret = NQuantLibcPINVOKE.EnergyVanillaSwapExt_payReceive(swigCPtr);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double fixedPrice() {
    double ret = NQuantLibcPINVOKE.EnergyVanillaSwapExt_fixedPrice(swigCPtr);
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
